TemplateAutomationTrigger {
    nodejs = 'node_v_20.0.7'
    agent = 'automation-medium'
    schedule = '0 8 * * 2'
    commandRun = 'npm run automation:test'
    automation_type = 'playwright'
    report_type = 'jenkins'
    vars = [
        
    ]
}
